In [2]:
import pandas as pd
import numpy as np

reviews = pd.read_pickle('features/tor_reviews.p')
bus_rev_res_offset = pd.read_pickle('features/bus_rev_res_offset_hu.p')
attr = pd.read_pickle('features/tor_attributes_features.p')
users = pd.read_pickle('features/tor_users_features.p')
user_rev_res_offset = pd.read_pickle('features/user_rev_res_offset_hu.p')
ds = pd.read_pickle('features/dinesafe.p')
vs = pd.read_pickle('features/vec_sim.p')

In [3]:
df = reviews.drop(['cool', 'funny', 'useful'], axis=1)
df.date = df.date.astype(np.datetime64)

df = pd.merge(df, vs, on='review_id')
df = pd.merge(df, bus_rev_res_offset, on=['business_id', 'date'])
df = pd.merge(df, user_rev_res_offset, on=['user_id', 'date'])

In [4]:
df = pd.merge(df, attr, right_index=True, left_on='business_id')
df = pd.merge(df, users, right_index=True, left_on='user_id')
df = pd.merge(df, ds, right_index=True, left_on='business_id')

In [5]:
df = df.set_index('review_id')

In [6]:
df.to_pickle('features/join.p')

In [7]:
df.head()

,business_id,date,stars,text,user_id,cos_sim_all,cos_sim_noun,cos_sim_adj,cos_sim_verb,count_review_x,...,number of years of elite,number of friends,membershiptime,dinesafe_rev_closed,dinesafe_rev_condpass,dinesafe_rev_pass,dinesafe_status_crucial,dinesafe_status_minor,dinesafe_status_na,dinesafe_status_significant
review_id,,,,,,,,,,,,,,,,,,,,,
kS4hrhEScwB9V5JATYjvVQ,f5O7v_X_jCg2itqacRfxhg,2017-10-12,5,Sansotei serves some top notch ramen. They tak...,hxqo4NyJFfeOmuoVi--s1A,NaN,NaN,NaN,NaN,286.0,...,1,1,717,0,0,1,0,0,0,0
aJONbWA2xEL2LjMiaVw0Lw,f5O7v_X_jCg2itqacRfxhg,2017-10-12,5,Rarely have I seen the bottom of my ramen bowl...,8lofUN7rFkwT2bw4b5SM4g,0.991579,0.983929,0.979287,0.985941,286.0,...,1,3,341,0,0,1,0,0,0,0
08b6lYBqj4D2YIaZ2Q-8eg,f5O7v_X_jCg2itqacRfxhg,2017-10-12,5,We popped in to have a quick warm bowl of Japa...,YtsfvF2P5rpwmmHijXRmWg,0.989517,0.986888,0.989366,0.987269,286.0,...,1,29,356,0,0,1,0,0,0,0
s6bj18Bk0auCEMMS7PeXuw,f5O7v_X_jCg2itqacRfxhg,2015-05-10,4,"yes, the noodle broth is amazing relative to k...",A9PzIlg1jlezCcpuN9V8UQ,0.986587,0.986441,0.985518,0.988582,217.0,...,5,16,2550,0,0,1,0,0,0,0
x_KxG5B6Bc_OK8DwtSEfaQ,f5O7v_X_jCg2itqacRfxhg,2017-04-19,5,"Very friendly, nice simple decor and the food ...",jdf15x7YE69Dd2a3o0hAag,0.979901,0.943232,0.945843,0.963646,309.0,...,1,1,2533,0,0,1,0,0,0,0